// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/orbekk/protobuf/Data.proto

package com.orbekk.protobuf;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
    }
    
    // optional string full_service_name = 1;
    public static final int FULL_SERVICE_NAME_FIELD_NUMBER = 1;
    private boolean hasFullServiceName;
    private java.lang.String fullServiceName_ = "";
    public boolean hasFullServiceName() { return hasFullServiceName; }
    public java.lang.String getFullServiceName() { return fullServiceName_; }
    
    // optional string method_name = 2;
    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private boolean hasMethodName;
    private java.lang.String methodName_ = "";
    public boolean hasMethodName() { return hasMethodName; }
    public java.lang.String getMethodName() { return methodName_; }
    
    // optional bytes request_proto = 3;
    public static final int REQUEST_PROTO_FIELD_NUMBER = 3;
    private boolean hasRequestProto;
    private com.google.protobuf.ByteString requestProto_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasRequestProto() { return hasRequestProto; }
    public com.google.protobuf.ByteString getRequestProto() { return requestProto_; }
    
    // optional int64 request_id = 4;
    public static final int REQUEST_ID_FIELD_NUMBER = 4;
    private boolean hasRequestId;
    private long requestId_ = 0L;
    public boolean hasRequestId() { return hasRequestId; }
    public long getRequestId() { return requestId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFullServiceName()) {
        output.writeString(1, getFullServiceName());
      }
      if (hasMethodName()) {
        output.writeString(2, getMethodName());
      }
      if (hasRequestProto()) {
        output.writeBytes(3, getRequestProto());
      }
      if (hasRequestId()) {
        output.writeInt64(4, getRequestId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFullServiceName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFullServiceName());
      }
      if (hasMethodName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMethodName());
      }
      if (hasRequestProto()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequestProto());
      }
      if (hasRequestId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getRequestId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.orbekk.protobuf.Data.Request result;
      
      // Construct using com.orbekk.protobuf.Data.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.orbekk.protobuf.Data.Request();
        return builder;
      }
      
      protected com.orbekk.protobuf.Data.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.orbekk.protobuf.Data.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.Request.getDescriptor();
      }
      
      public com.orbekk.protobuf.Data.Request getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.orbekk.protobuf.Data.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.orbekk.protobuf.Data.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.orbekk.protobuf.Data.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.orbekk.protobuf.Data.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Request) {
          return mergeFrom((com.orbekk.protobuf.Data.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orbekk.protobuf.Data.Request other) {
        if (other == com.orbekk.protobuf.Data.Request.getDefaultInstance()) return this;
        if (other.hasFullServiceName()) {
          setFullServiceName(other.getFullServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasRequestProto()) {
          setRequestProto(other.getRequestProto());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFullServiceName(input.readString());
              break;
            }
            case 18: {
              setMethodName(input.readString());
              break;
            }
            case 26: {
              setRequestProto(input.readBytes());
              break;
            }
            case 32: {
              setRequestId(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional string full_service_name = 1;
      public boolean hasFullServiceName() {
        return result.hasFullServiceName();
      }
      public java.lang.String getFullServiceName() {
        return result.getFullServiceName();
      }
      public Builder setFullServiceName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFullServiceName = true;
        result.fullServiceName_ = value;
        return this;
      }
      public Builder clearFullServiceName() {
        result.hasFullServiceName = false;
        result.fullServiceName_ = getDefaultInstance().getFullServiceName();
        return this;
      }
      
      // optional string method_name = 2;
      public boolean hasMethodName() {
        return result.hasMethodName();
      }
      public java.lang.String getMethodName() {
        return result.getMethodName();
      }
      public Builder setMethodName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMethodName = true;
        result.methodName_ = value;
        return this;
      }
      public Builder clearMethodName() {
        result.hasMethodName = false;
        result.methodName_ = getDefaultInstance().getMethodName();
        return this;
      }
      
      // optional bytes request_proto = 3;
      public boolean hasRequestProto() {
        return result.hasRequestProto();
      }
      public com.google.protobuf.ByteString getRequestProto() {
        return result.getRequestProto();
      }
      public Builder setRequestProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequestProto = true;
        result.requestProto_ = value;
        return this;
      }
      public Builder clearRequestProto() {
        result.hasRequestProto = false;
        result.requestProto_ = getDefaultInstance().getRequestProto();
        return this;
      }
      
      // optional int64 request_id = 4;
      public boolean hasRequestId() {
        return result.hasRequestId();
      }
      public long getRequestId() {
        return result.getRequestId();
      }
      public Builder setRequestId(long value) {
        result.hasRequestId = true;
        result.requestId_ = value;
        return this;
      }
      public Builder clearRequestId() {
        result.hasRequestId = false;
        result.requestId_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      com.orbekk.protobuf.Data.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Request)
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {
      initFields();
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;
    }
    
    public enum RpcError
        implements com.google.protobuf.ProtocolMessageEnum {
      UNKNOWN_SERVICE(0, 0),
      UNKNOWN_METHOD(1, 1),
      CANCELED(2, 2),
      INVALID_PROTOBUF(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static RpcError valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN_SERVICE;
          case 1: return UNKNOWN_METHOD;
          case 2: return CANCELED;
          case 3: return INVALID_PROTOBUF;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RpcError>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RpcError>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RpcError>() {
              public RpcError findValueByNumber(int number) {
                return RpcError.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.Response.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final RpcError[] VALUES = {
        UNKNOWN_SERVICE, UNKNOWN_METHOD, CANCELED, INVALID_PROTOBUF, 
      };
      public static RpcError valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private RpcError(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.orbekk.protobuf.Data.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:com.orbekk.protobuf.Response.RpcError)
    }
    
    // optional bytes response_proto = 1;
    public static final int RESPONSE_PROTO_FIELD_NUMBER = 1;
    private boolean hasResponseProto;
    private com.google.protobuf.ByteString responseProto_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasResponseProto() { return hasResponseProto; }
    public com.google.protobuf.ByteString getResponseProto() { return responseProto_; }
    
    // optional .com.orbekk.protobuf.Response.RpcError error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private boolean hasError;
    private com.orbekk.protobuf.Data.Response.RpcError error_;
    public boolean hasError() { return hasError; }
    public com.orbekk.protobuf.Data.Response.RpcError getError() { return error_; }
    
    // optional int64 request_id = 5;
    public static final int REQUEST_ID_FIELD_NUMBER = 5;
    private boolean hasRequestId;
    private long requestId_ = 0L;
    public boolean hasRequestId() { return hasRequestId; }
    public long getRequestId() { return requestId_; }
    
    // optional bool hasFailed = 4;
    public static final int HASFAILED_FIELD_NUMBER = 4;
    private boolean hasHasFailed;
    private boolean hasFailed_ = false;
    public boolean hasHasFailed() { return hasHasFailed; }
    public boolean getHasFailed() { return hasFailed_; }
    
    // optional bool canceled = 6;
    public static final int CANCELED_FIELD_NUMBER = 6;
    private boolean hasCanceled;
    private boolean canceled_ = false;
    public boolean hasCanceled() { return hasCanceled; }
    public boolean getCanceled() { return canceled_; }
    
    // optional bool done = 7 [default = true];
    public static final int DONE_FIELD_NUMBER = 7;
    private boolean hasDone;
    private boolean done_ = true;
    public boolean hasDone() { return hasDone; }
    public boolean getDone() { return done_; }
    
    // optional string error_text = 3;
    public static final int ERROR_TEXT_FIELD_NUMBER = 3;
    private boolean hasErrorText;
    private java.lang.String errorText_ = "";
    public boolean hasErrorText() { return hasErrorText; }
    public java.lang.String getErrorText() { return errorText_; }
    
    private void initFields() {
      error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasResponseProto()) {
        output.writeBytes(1, getResponseProto());
      }
      if (hasError()) {
        output.writeEnum(2, getError().getNumber());
      }
      if (hasErrorText()) {
        output.writeString(3, getErrorText());
      }
      if (hasHasFailed()) {
        output.writeBool(4, getHasFailed());
      }
      if (hasRequestId()) {
        output.writeInt64(5, getRequestId());
      }
      if (hasCanceled()) {
        output.writeBool(6, getCanceled());
      }
      if (hasDone()) {
        output.writeBool(7, getDone());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasResponseProto()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResponseProto());
      }
      if (hasError()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getError().getNumber());
      }
      if (hasErrorText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getErrorText());
      }
      if (hasHasFailed()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getHasFailed());
      }
      if (hasRequestId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getRequestId());
      }
      if (hasCanceled()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, getCanceled());
      }
      if (hasDone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getDone());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.orbekk.protobuf.Data.Response result;
      
      // Construct using com.orbekk.protobuf.Data.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.orbekk.protobuf.Data.Response();
        return builder;
      }
      
      protected com.orbekk.protobuf.Data.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.orbekk.protobuf.Data.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.Response.getDescriptor();
      }
      
      public com.orbekk.protobuf.Data.Response getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.orbekk.protobuf.Data.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.orbekk.protobuf.Data.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.orbekk.protobuf.Data.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.orbekk.protobuf.Data.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Response) {
          return mergeFrom((com.orbekk.protobuf.Data.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orbekk.protobuf.Data.Response other) {
        if (other == com.orbekk.protobuf.Data.Response.getDefaultInstance()) return this;
        if (other.hasResponseProto()) {
          setResponseProto(other.getResponseProto());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasHasFailed()) {
          setHasFailed(other.getHasFailed());
        }
        if (other.hasCanceled()) {
          setCanceled(other.getCanceled());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        if (other.hasErrorText()) {
          setErrorText(other.getErrorText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setResponseProto(input.readBytes());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.orbekk.protobuf.Data.Response.RpcError value = com.orbekk.protobuf.Data.Response.RpcError.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setError(value);
              }
              break;
            }
            case 26: {
              setErrorText(input.readString());
              break;
            }
            case 32: {
              setHasFailed(input.readBool());
              break;
            }
            case 40: {
              setRequestId(input.readInt64());
              break;
            }
            case 48: {
              setCanceled(input.readBool());
              break;
            }
            case 56: {
              setDone(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional bytes response_proto = 1;
      public boolean hasResponseProto() {
        return result.hasResponseProto();
      }
      public com.google.protobuf.ByteString getResponseProto() {
        return result.getResponseProto();
      }
      public Builder setResponseProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasResponseProto = true;
        result.responseProto_ = value;
        return this;
      }
      public Builder clearResponseProto() {
        result.hasResponseProto = false;
        result.responseProto_ = getDefaultInstance().getResponseProto();
        return this;
      }
      
      // optional .com.orbekk.protobuf.Response.RpcError error = 2;
      public boolean hasError() {
        return result.hasError();
      }
      public com.orbekk.protobuf.Data.Response.RpcError getError() {
        return result.getError();
      }
      public Builder setError(com.orbekk.protobuf.Data.Response.RpcError value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasError = true;
        result.error_ = value;
        return this;
      }
      public Builder clearError() {
        result.hasError = false;
        result.error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
        return this;
      }
      
      // optional int64 request_id = 5;
      public boolean hasRequestId() {
        return result.hasRequestId();
      }
      public long getRequestId() {
        return result.getRequestId();
      }
      public Builder setRequestId(long value) {
        result.hasRequestId = true;
        result.requestId_ = value;
        return this;
      }
      public Builder clearRequestId() {
        result.hasRequestId = false;
        result.requestId_ = 0L;
        return this;
      }
      
      // optional bool hasFailed = 4;
      public boolean hasHasFailed() {
        return result.hasHasFailed();
      }
      public boolean getHasFailed() {
        return result.getHasFailed();
      }
      public Builder setHasFailed(boolean value) {
        result.hasHasFailed = true;
        result.hasFailed_ = value;
        return this;
      }
      public Builder clearHasFailed() {
        result.hasHasFailed = false;
        result.hasFailed_ = false;
        return this;
      }
      
      // optional bool canceled = 6;
      public boolean hasCanceled() {
        return result.hasCanceled();
      }
      public boolean getCanceled() {
        return result.getCanceled();
      }
      public Builder setCanceled(boolean value) {
        result.hasCanceled = true;
        result.canceled_ = value;
        return this;
      }
      public Builder clearCanceled() {
        result.hasCanceled = false;
        result.canceled_ = false;
        return this;
      }
      
      // optional bool done = 7 [default = true];
      public boolean hasDone() {
        return result.hasDone();
      }
      public boolean getDone() {
        return result.getDone();
      }
      public Builder setDone(boolean value) {
        result.hasDone = true;
        result.done_ = value;
        return this;
      }
      public Builder clearDone() {
        result.hasDone = false;
        result.done_ = true;
        return this;
      }
      
      // optional string error_text = 3;
      public boolean hasErrorText() {
        return result.hasErrorText();
      }
      public java.lang.String getErrorText() {
        return result.getErrorText();
      }
      public Builder setErrorText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasErrorText = true;
        result.errorText_ = value;
        return this;
      }
      public Builder clearErrorText() {
        result.hasErrorText = false;
        result.errorText_ = getDefaultInstance().getErrorText();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      com.orbekk.protobuf.Data.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/java/com/orbekk/protobuf/Data" +
      ".proto\022\023com.orbekk.protobuf\"d\n\007Request\022\031" +
      "\n\021full_service_name\030\001 \001(\t\022\023\n\013method_name" +
      "\030\002 \001(\t\022\025\n\rrequest_proto\030\003 \001(\014\022\022\n\nrequest" +
      "_id\030\004 \001(\003\"\223\002\n\010Response\022\026\n\016response_proto" +
      "\030\001 \001(\014\0225\n\005error\030\002 \001(\0162&.com.orbekk.proto" +
      "buf.Response.RpcError\022\022\n\nrequest_id\030\005 \001(" +
      "\003\022\021\n\thasFailed\030\004 \001(\010\022\020\n\010canceled\030\006 \001(\010\022\022" +
      "\n\004done\030\007 \001(\010:\004true\022\022\n\nerror_text\030\003 \001(\t\"W" +
      "\n\010RpcError\022\023\n\017UNKNOWN_SERVICE\020\000\022\022\n\016UNKNO",
      "WN_METHOD\020\001\022\014\n\010CANCELED\020\002\022\024\n\020INVALID_PRO" +
      "TOBUF\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_orbekk_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_orbekk_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_orbekk_protobuf_Request_descriptor,
              new java.lang.String[] { "FullServiceName", "MethodName", "RequestProto", "RequestId", },
              com.orbekk.protobuf.Data.Request.class,
              com.orbekk.protobuf.Data.Request.Builder.class);
          internal_static_com_orbekk_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_orbekk_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_orbekk_protobuf_Response_descriptor,
              new java.lang.String[] { "ResponseProto", "Error", "RequestId", "HasFailed", "Canceled", "Done", "ErrorText", },
              com.orbekk.protobuf.Data.Response.class,
              com.orbekk.protobuf.Data.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
