// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/orbekk/protobuf/Data.proto

package com.orbekk.protobuf;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string full_service_name = 1;
    boolean hasFullServiceName();
    String getFullServiceName();
    
    // optional string method_name = 2;
    boolean hasMethodName();
    String getMethodName();
    
    // optional bytes request_proto = 3;
    boolean hasRequestProto();
    com.google.protobuf.ByteString getRequestProto();
    
    // optional int64 request_id = 4;
    boolean hasRequestId();
    long getRequestId();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string full_service_name = 1;
    public static final int FULL_SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object fullServiceName_;
    public boolean hasFullServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFullServiceName() {
      java.lang.Object ref = fullServiceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fullServiceName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFullServiceNameBytes() {
      java.lang.Object ref = fullServiceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fullServiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string method_name = 2;
    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes request_proto = 3;
    public static final int REQUEST_PROTO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestProto_;
    public boolean hasRequestProto() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getRequestProto() {
      return requestProto_;
    }
    
    // optional int64 request_id = 4;
    public static final int REQUEST_ID_FIELD_NUMBER = 4;
    private long requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getRequestId() {
      return requestId_;
    }
    
    private void initFields() {
      fullServiceName_ = "";
      methodName_ = "";
      requestProto_ = com.google.protobuf.ByteString.EMPTY;
      requestId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFullServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestProto_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, requestId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFullServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestProto_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, requestId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orbekk.protobuf.Data.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
      }
      
      // Construct using com.orbekk.protobuf.Data.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fullServiceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.Request.getDescriptor();
      }
      
      public com.orbekk.protobuf.Data.Request getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Request.getDefaultInstance();
      }
      
      public com.orbekk.protobuf.Data.Request build() {
        com.orbekk.protobuf.Data.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orbekk.protobuf.Data.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orbekk.protobuf.Data.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orbekk.protobuf.Data.Request buildPartial() {
        com.orbekk.protobuf.Data.Request result = new com.orbekk.protobuf.Data.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullServiceName_ = fullServiceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestProto_ = requestProto_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestId_ = requestId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Request) {
          return mergeFrom((com.orbekk.protobuf.Data.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orbekk.protobuf.Data.Request other) {
        if (other == com.orbekk.protobuf.Data.Request.getDefaultInstance()) return this;
        if (other.hasFullServiceName()) {
          setFullServiceName(other.getFullServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasRequestProto()) {
          setRequestProto(other.getRequestProto());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fullServiceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestProto_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              requestId_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string full_service_name = 1;
      private java.lang.Object fullServiceName_ = "";
      public boolean hasFullServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFullServiceName() {
        java.lang.Object ref = fullServiceName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fullServiceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFullServiceName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullServiceName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFullServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullServiceName_ = getDefaultInstance().getFullServiceName();
        onChanged();
        return this;
      }
      void setFullServiceName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        fullServiceName_ = value;
        onChanged();
      }
      
      // optional string method_name = 2;
      private java.lang.Object methodName_ = "";
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      void setMethodName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
      }
      
      // optional bytes request_proto = 3;
      private com.google.protobuf.ByteString requestProto_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasRequestProto() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getRequestProto() {
        return requestProto_;
      }
      public Builder setRequestProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestProto_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestProto() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestProto_ = getDefaultInstance().getRequestProto();
        onChanged();
        return this;
      }
      
      // optional int64 request_id = 4;
      private long requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestId_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes response_proto = 1;
    boolean hasResponseProto();
    com.google.protobuf.ByteString getResponseProto();
    
    // optional .com.orbekk.protobuf.Response.RpcError error = 2;
    boolean hasError();
    com.orbekk.protobuf.Data.Response.RpcError getError();
    
    // optional int64 request_id = 5;
    boolean hasRequestId();
    long getRequestId();
    
    // optional bool hasFailed = 4;
    boolean hasHasFailed();
    boolean getHasFailed();
    
    // optional bool canceled = 6;
    boolean hasCanceled();
    boolean getCanceled();
    
    // optional bool done = 7 [default = true];
    boolean hasDone();
    boolean getDone();
    
    // optional string error_text = 3;
    boolean hasErrorText();
    String getErrorText();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;
    }
    
    public enum RpcError
        implements com.google.protobuf.ProtocolMessageEnum {
      UNKNOWN_SERVICE(0, 0),
      UNKNOWN_METHOD(1, 1),
      CANCELED(2, 2),
      INVALID_PROTOBUF(3, 3),
      ;
      
      public static final int UNKNOWN_SERVICE_VALUE = 0;
      public static final int UNKNOWN_METHOD_VALUE = 1;
      public static final int CANCELED_VALUE = 2;
      public static final int INVALID_PROTOBUF_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static RpcError valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN_SERVICE;
          case 1: return UNKNOWN_METHOD;
          case 2: return CANCELED;
          case 3: return INVALID_PROTOBUF;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RpcError>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RpcError>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RpcError>() {
              public RpcError findValueByNumber(int number) {
                return RpcError.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.Response.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final RpcError[] VALUES = {
        UNKNOWN_SERVICE, UNKNOWN_METHOD, CANCELED, INVALID_PROTOBUF, 
      };
      
      public static RpcError valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private RpcError(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.orbekk.protobuf.Response.RpcError)
    }
    
    private int bitField0_;
    // optional bytes response_proto = 1;
    public static final int RESPONSE_PROTO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString responseProto_;
    public boolean hasResponseProto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getResponseProto() {
      return responseProto_;
    }
    
    // optional .com.orbekk.protobuf.Response.RpcError error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private com.orbekk.protobuf.Data.Response.RpcError error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.orbekk.protobuf.Data.Response.RpcError getError() {
      return error_;
    }
    
    // optional int64 request_id = 5;
    public static final int REQUEST_ID_FIELD_NUMBER = 5;
    private long requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getRequestId() {
      return requestId_;
    }
    
    // optional bool hasFailed = 4;
    public static final int HASFAILED_FIELD_NUMBER = 4;
    private boolean hasFailed_;
    public boolean hasHasFailed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getHasFailed() {
      return hasFailed_;
    }
    
    // optional bool canceled = 6;
    public static final int CANCELED_FIELD_NUMBER = 6;
    private boolean canceled_;
    public boolean hasCanceled() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getCanceled() {
      return canceled_;
    }
    
    // optional bool done = 7 [default = true];
    public static final int DONE_FIELD_NUMBER = 7;
    private boolean done_;
    public boolean hasDone() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getDone() {
      return done_;
    }
    
    // optional string error_text = 3;
    public static final int ERROR_TEXT_FIELD_NUMBER = 3;
    private java.lang.Object errorText_;
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getErrorText() {
      java.lang.Object ref = errorText_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorText_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      responseProto_ = com.google.protobuf.ByteString.EMPTY;
      error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
      requestId_ = 0L;
      hasFailed_ = false;
      canceled_ = false;
      done_ = true;
      errorText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, error_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(3, getErrorTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, hasFailed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(5, requestId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, canceled_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(7, done_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, error_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasFailed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, requestId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, canceled_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, done_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orbekk.protobuf.Data.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;
      }
      
      // Construct using com.orbekk.protobuf.Data.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        responseProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasFailed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        canceled_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        done_ = true;
        bitField0_ = (bitField0_ & ~0x00000020);
        errorText_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.Response.getDescriptor();
      }
      
      public com.orbekk.protobuf.Data.Response getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Response.getDefaultInstance();
      }
      
      public com.orbekk.protobuf.Data.Response build() {
        com.orbekk.protobuf.Data.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orbekk.protobuf.Data.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orbekk.protobuf.Data.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orbekk.protobuf.Data.Response buildPartial() {
        com.orbekk.protobuf.Data.Response result = new com.orbekk.protobuf.Data.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseProto_ = responseProto_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasFailed_ = hasFailed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.canceled_ = canceled_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.done_ = done_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.errorText_ = errorText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Response) {
          return mergeFrom((com.orbekk.protobuf.Data.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orbekk.protobuf.Data.Response other) {
        if (other == com.orbekk.protobuf.Data.Response.getDefaultInstance()) return this;
        if (other.hasResponseProto()) {
          setResponseProto(other.getResponseProto());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasHasFailed()) {
          setHasFailed(other.getHasFailed());
        }
        if (other.hasCanceled()) {
          setCanceled(other.getCanceled());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        if (other.hasErrorText()) {
          setErrorText(other.getErrorText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              responseProto_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.orbekk.protobuf.Data.Response.RpcError value = com.orbekk.protobuf.Data.Response.RpcError.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                error_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000040;
              errorText_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hasFailed_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              requestId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              canceled_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              done_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes response_proto = 1;
      private com.google.protobuf.ByteString responseProto_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasResponseProto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getResponseProto() {
        return responseProto_;
      }
      public Builder setResponseProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseProto_ = value;
        onChanged();
        return this;
      }
      public Builder clearResponseProto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseProto_ = getDefaultInstance().getResponseProto();
        onChanged();
        return this;
      }
      
      // optional .com.orbekk.protobuf.Response.RpcError error = 2;
      private com.orbekk.protobuf.Data.Response.RpcError error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.orbekk.protobuf.Data.Response.RpcError getError() {
        return error_;
      }
      public Builder setError(com.orbekk.protobuf.Data.Response.RpcError value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE;
        onChanged();
        return this;
      }
      
      // optional int64 request_id = 5;
      private long requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional bool hasFailed = 4;
      private boolean hasFailed_ ;
      public boolean hasHasFailed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getHasFailed() {
        return hasFailed_;
      }
      public Builder setHasFailed(boolean value) {
        bitField0_ |= 0x00000008;
        hasFailed_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasFailed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasFailed_ = false;
        onChanged();
        return this;
      }
      
      // optional bool canceled = 6;
      private boolean canceled_ ;
      public boolean hasCanceled() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getCanceled() {
        return canceled_;
      }
      public Builder setCanceled(boolean value) {
        bitField0_ |= 0x00000010;
        canceled_ = value;
        onChanged();
        return this;
      }
      public Builder clearCanceled() {
        bitField0_ = (bitField0_ & ~0x00000010);
        canceled_ = false;
        onChanged();
        return this;
      }
      
      // optional bool done = 7 [default = true];
      private boolean done_ = true;
      public boolean hasDone() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getDone() {
        return done_;
      }
      public Builder setDone(boolean value) {
        bitField0_ |= 0x00000020;
        done_ = value;
        onChanged();
        return this;
      }
      public Builder clearDone() {
        bitField0_ = (bitField0_ & ~0x00000020);
        done_ = true;
        onChanged();
        return this;
      }
      
      // optional string error_text = 3;
      private java.lang.Object errorText_ = "";
      public boolean hasErrorText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getErrorText() {
        java.lang.Object ref = errorText_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorText_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        errorText_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        errorText_ = getDefaultInstance().getErrorText();
        onChanged();
        return this;
      }
      void setErrorText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        errorText_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/java/com/orbekk/protobuf/Data" +
      ".proto\022\023com.orbekk.protobuf\"d\n\007Request\022\031" +
      "\n\021full_service_name\030\001 \001(\t\022\023\n\013method_name" +
      "\030\002 \001(\t\022\025\n\rrequest_proto\030\003 \001(\014\022\022\n\nrequest" +
      "_id\030\004 \001(\003\"\223\002\n\010Response\022\026\n\016response_proto" +
      "\030\001 \001(\014\0225\n\005error\030\002 \001(\0162&.com.orbekk.proto" +
      "buf.Response.RpcError\022\022\n\nrequest_id\030\005 \001(" +
      "\003\022\021\n\thasFailed\030\004 \001(\010\022\020\n\010canceled\030\006 \001(\010\022\022" +
      "\n\004done\030\007 \001(\010:\004true\022\022\n\nerror_text\030\003 \001(\t\"W" +
      "\n\010RpcError\022\023\n\017UNKNOWN_SERVICE\020\000\022\022\n\016UNKNO",
      "WN_METHOD\020\001\022\014\n\010CANCELED\020\002\022\024\n\020INVALID_PRO" +
      "TOBUF\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_orbekk_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_orbekk_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_orbekk_protobuf_Request_descriptor,
              new java.lang.String[] { "FullServiceName", "MethodName", "RequestProto", "RequestId", },
              com.orbekk.protobuf.Data.Request.class,
              com.orbekk.protobuf.Data.Request.Builder.class);
          internal_static_com_orbekk_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_orbekk_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_orbekk_protobuf_Response_descriptor,
              new java.lang.String[] { "ResponseProto", "Error", "RequestId", "HasFailed", "Canceled", "Done", "ErrorText", },
              com.orbekk.protobuf.Data.Response.class,
              com.orbekk.protobuf.Data.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
